#!/bin/bash
function my_error() {
    # エラー処理
    echo
    echo "Please put \"autozoom2\" folder below" $username "and try again."
    sleep 5
    exit 1
}
# rm -rf .git

if [ "$(uname)" == 'Darwin' ]; then
  OS="Mac"
elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
  OS="Linux"
else
  echo "Your platform ($(uname -a)) is not supported."
  exit 1
fi
echo your os is $OS

python3 -c "import tkinter;print(tkinter.TkVersion)"
if test $? -eq 1; then
echo "This App needs python3 and tkinter(from python). Please install them and retry."
exit 1
fi

path1=$(cd $(dirname $0);pwd)
cd 
path=`pwd`
username=`python3 $path1/forinstall/getname.py "$path"`
cd $path1
cd ..
mv ./autozoom2 ~/
cd ~/autozoom2 || my_error
chmod +x ./src/autozoom2
chmod +x ./forinstall/autozoom2.desktop
if [ "$OS" = "Mac" ];then
  cp ./src/autozoom2 ~/Desktop/
elif [ "$OS" = "Linux" ];then
  sed -i -e "s/kakeru/$username/g" ./forinstall/autozoom2.desktop
  cp ./forinstall/autozoom2.desktop ~/.local/share/applications
  echo alias autozoom2=\"bash ~/autozoom2/src/autozoom2\" >> ~/.bashrc
  alias autozoom2="bash ~/autozoom2/src/autozoom2"
  source ~/.bashrc
fi

if test $? -eq 0; then
echo
echo --------- AUTOZOOM2 ---------
echo Welcome $username
echo successfully installed
echo -----------------------------
echo
echo
fi
